CREATE TABLE Person
(            //TODO При удалении не будет освобождаться ID. Можно ли этого избежать?
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio      varchar(60),
    gender   varchar(30),
    weight   integer,
    h        integer,
    age      integer,
    calories integer
);

//TODO не создана таблица
CREATE TABLE Ration
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories integer,
    BZHU varchar(10),
    weight integer,
    description varchar
);



INSERT INTO Person (fio, gender, h, age, weight, calories)
values ('Pankratova U.A.', 'WOMAN', 160, 21, 52, 2350);

INSERT INTO Person (fio, gender, h, age, weight, calories)
values ('Naimushin S.M.', 'MAN', 166, 22, 70, 2700);

SELECT *
FROM Ration;

delete
from Person
where id = 5;

DROP TABLE Person;
DROP TABLE Ration;
