CREATE TABLE Person
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio      varchar(60),
    gender   varchar(30),
    weight   integer,
    h        integer,
    age      integer,
    calories integer
);

/*CREATE TABLE Ration
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories integer,
    BZHU varchar(10),
    weight integer,
    description varchar
);*/

CREATE TABLE Products
(
  product_id                       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name                     VARCHAR(255) NOT NULL,
  product_calories_per_100g        INTEGER,
  product_daily_norm_per_person    INTEGER,
  product_proteins                 DOUBLE PRECISION,
  product_fats                     DOUBLE PRECISION,
  product_carbohydrates            DOUBLE PRECISION,
  product_digestibility_percentage INTEGER
);

CREATE TABLE Product_types
(
  type_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name VARCHAR(255) NOT NULL
);

CREATE TABLE mix
(
  type_id    INTEGER,
  product_id INTEGER,
  PRIMARY KEY (type_id, product_id),
  FOREIGN KEY (type_id) REFERENCES Product_types (type_id),
  FOREIGN KEY (product_id) REFERENCES Products (product_id)
);

INSERT INTO Person (fio, gender, h, age, weight, calories)
values ('Pankratova U.A.', 'WOMAN', 160, 21, 52, 2350);

INSERT INTO Person (fio, gender, h, age, weight, calories)
values ('Naimushin S.M.', 'MAN', 170, 22, 77, 3024);

delete
from Person
where id = 5;

DROP TABLE Person;

